### ISSUE TITLE
Window names getting overwritten

### ISSUE THREAD

**Issue by jlipps** [tmuxinator/tmuxinator#141]
Hi, thanks for tmuxinator!

One issue I'm having on day 1 is that the window names tmuxinator sets are getting overwritten by the names of the commands being run. I see the tmuxinator name flash up for a second and then as soon as the initial commands are run they disappear.

This might be default behavior but I'd love to see just the window index and name, regardless of what process is running in the window.

Is there a way to to do this?

**Comment by safaci2000** [comment]
Thanks for this.  I had the same issue.  tmux 1.9a.

**Comment by TauPan** [comment]
I had a problem using the recommended option, since I specifically want zsh windows to be able to set the window name (via escape sequence), but not if I start most other commands.

My solution for now is to make an explicit exception for shell windows, i.e. I have
```
set-window-option -g allow-rename off
set-window-option -g automatic-rename off
```

in my tmux.conf and later:
```
# Since (automatic)-rename is off, we make an exception for shell windows:
bind-key c new-window \; set-window-option -q allow-rename on \; set-window-option  -q automatic-rename on
```

Which allows shell windows to set the window name.
