### ISSUE TITLE
Detach session automatically

### ISSUE THREAD

**Issue by astrodad** [tmuxinator/tmuxinator#191]
Hello,

I'm looking to launch a project at startup and then detach immediately so that other people can use the session. Is there any way to do that? I tried sending in a C-b D and ^b D as the second line of the panel array but that just sent that text to the pane. Any ideas?

**Comment by rightaway** [comment]
+1 for the startup option tmux_detached like in https://github.com/tmuxinator/tmuxinator/pull/284

**Comment by ZeusTheTrueGod** [comment]
Guys, there is an easy trick, just add this in ```windows:``` in your .yml config file
``` -detach: tmux detach && tmux kill-window```

**Comment by Soliah** [comment]
Addressed by #293

**Comment by lougreenwood** [comment]
I'm not sure, but I don't know if this is really addressed.

For my use case I sometimes want to start it detached, others not, so using a `post` isn't possible because I lose optionality.

Ideally I'd prefer to just do `tmuxinator start myproject -D` and control whether to start detached from a flag...

**Comment by Drew-Daniels** [comment]
@lougreenwood Agree - I don't want to have to always start a tmuxinator project detached or attached. Would be very nice if we could default to starting tmux sessions attached, but only start detached if a `--detached` or `-d` flag is provided when we  initially create the session.
