### ISSUE TITLE
Naming with namespace cause bug when start  a project

### ISSUE THREAD

**Issue by st0012** [tmuxinator/tmuxinator#347]
I have a project called `apriori` and the other called `apriori-test`. The issue is that after I started `apriori-test` and want to start the `apriori` project, it will open the `apriori-test` session instead. But if I started `apriori` first and want to start `apriori-test`, it works without any issue. And the `new` command also works fine.
How can I solve this?

**Comment by anderslime** [comment]
I'm having this issue too.

**Comment by magicalbanana** [comment]
I think it's how the aliasing works. I can see if I can take a look at this and have this fixed.

**Comment by ethagnawl** [comment]
This problem appears to be caused by Tmux's `has-session` being over-eager. 

If I have an active Tmux session called "first-second" and execute: `tmux start-server\; has-session -t first 2>/dev/null`, then `$?` will be `0` (i.e. the session exists). 

That command is what's used in the script created by lib/tmuxinator/assets/template.erb to determine whether or not the session needs to be created and is why `mux apriori` behaves the way it does (when apriori-test is already running).

We could change that command to something like: `<%= tmux %> ls | grep ^<%= name %>: 2>/dev/null`. However, I 1) haven't figured out a good way to write a failing test for this bug and 2) am not sure how portable that command is.
