### ISSUE TITLE
XDG base directory support

### ISSUE THREAD

**Issue by Yamakaky** [tmuxinator/tmuxinator#360]
See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
For tmuxinator, it would mean use `~/.config/tmuxinator` instead of/in addition to `~/.tmuxinator/`. It should not be difficult to add.

**Comment by suy** [comment]
To be pedantic: It should be `$XDG_CONFIG_HOME/tmuxinator`, with `$XDG_CONFIG_HOME` defaulting to ~/.config if unset. I think I can do this myself, if you are open to the change.

**Comment by adamstrickland** [comment]
@suy i can only speak for myself, but I'm open to the change, but in all honesty I don't know much about XDG and all that.  Some questions that would need to be addressed may be:

- Besides conforming to standard, does this buy us anything?
- What cost (e.g. complexity, etc.) do we pay for this?
- How would this affect non-XDG operating systems?

In all honesty, while I am generally in favor of conforming to standards, I have bigger fish to fry, so I personally wasn't going to take this on (simple though it may be) in part because I don't know much about the context.  But I'm not against it either, should someone want to make a FOSS contribution.

**Comment by geowa4** [comment]
For me, this would make my dotfiles repo much simpler. I'd essentially just have to clone into ~/.config.

**Comment by ncoop** [comment]
Suggestion on how to implement:

1. Look at `$XDG_CONFIG_HOME` if it's set and not empty, or else `~/.config/`. If `tmuxinator` dir (no dot) is there, use it.
1. Else use `~/.tmuxinator` if it exists.
1. Else there's no config dir, so create create it in the first location.
1. If the first location doesn't exist, create it in home.

This is similar to [how git config searches](https://git-scm.com/docs/git-config#FILES), and it's nice because users who don't want to organize with XDG don't even have to know about it. (Git config also has a custom env var that has higher priority.)

With this done, I think `mux doctor` should also report where the config dir is.

**Comment by J3RN** [comment]
@ncoop That sounds reasonable. In all honesty, I hate $HOME being crowded with dotfiles, so moving to using the `.config` directory seems ideal. I'll try to make time to start on this today.

**Comment by Soliah** [comment]
There's one more case where tmuxinator also supports looking at the current directory for a `.tmuxinator.yml` file.

**Comment by ncoop** [comment]
Today I learned there's a gem to facilitate this:
https://rubyworks.github.io/xdg/

**Comment by HaleTom** [comment]
What to do if both `$HOME/.tmuxinator` and `$XDG_CONFIG_HOME/.tmuxinator` exist? 

Options:

1. Take the `git` approach: process `$XDG_CONFIG_HOME/.tmuxinator` first, then override with any settings found in `$HOME/.tmuxinator` 

1. Warn that  `$HOME/.tmuxinator` exists and only `$XDG_CONFIG_HOME/.tmuxinator` will be used

1. Error and let the user sort it out

Option (1) is probably the hardest to implement but most inter-operable with (e.g.) existing scripts.

Would the project accept a pull-request for Options (2) or (3)?

**Comment by geowa4** [comment]
I want 3, but I'll take 2 as a temporary step to 3. If 1 is implemented, I will forget I have both and wonder why some change isn't taking effect.

**Comment by Yamakaky** [comment]
Yeah, I think you should warning for a bit then error.

**Comment by HaleTom** [comment]
@geowa4 you're right about (1 - `git` style) - I sometimes get strange behaviour when I copy `$XDG_CONFIG_HOME/git/config` to `~/.gitconfig` <sup>+</sup>

Let's say we (2) warn for now, how could we implement this in a way that allows transition to (3) erroring?

If a easy transition (for the users) is not possible, and erroring is the end goal, perhaps it's best to take a bit longer and exhibit that behaviour from the get-go?

<sup>+ Why you ask? Because I manage this ~300 line file in my [dotfiles git repository](https://github.com/HaleTom/dotfiles) [which tries to follow XDG base dirs].</sup>

**Comment by HaleTom** [comment]
I'm working on implementing this currently, and am going for option (1) so as to not break current behaviour.

When looking for a project called `project`, the current behaviour is to return the first filename found in:

1. A search of `~/.tmuxinator/` and all its subdirectories for the **first** file named `project.yml`
1. `./tmuxinator.yml`

There is no warning currently if a duplicate situation exists. I'm not saying that this is the desired behaviour, but I don't want to do more than resolve this issue and #462 at the moment.

I am writing a test to document this previously undocumented "first found" behaviour however.

**Comment by HaleTom** [comment]
I trust that you've now had time to check out #479.

What is the process for getting this merged in?

**Comment by ethagnawl** [comment]
Closed via #511 and #549.
