### ISSUE TITLE
Bash error when loading tmuxinator completion

### ISSUE THREAD

**Issue by J3RN** [tmuxinator/tmuxinator#395]
It appears that the following line doesn't work as expected in Bash:
```bash
type tmuxinator 2>&1 > /dev/null
```
Instead of redirecting the error to `/dev/null` when tmuxinator is not installed, it is printed to the console, which is annoying.

The following line should work instead:
```bash
type tmuxinator &> /dev/null
```

**Comment by cinaeco** [comment]
Oh, thanks for opening this issue. I didn't see it when I wrote https://github.com/tmuxinator/tmuxinator/pull/386#issuecomment-204603066. It did feel a bit weird continuing a discussion on a closed PR.

**Comment by cinaeco** [comment]
But yeah, can someone engage my point 2? I believe bash's completion doesn't require us to check for tmuxinator's existence, and is more flexible that way.

**Comment by J3RN** [comment]
@cinaeco Interesting point. I hadn't considered that. What I did notice is that after sourcing the completions, typing `mux <TAB>` on a machine that did not have tmuxinator installed resulting in an error being thrown. It's an edge case, you could say, relying on user error.

I guess my main concern with loading the bash completions regardless is that it breaks parity with the zsh implementation. If you source `rvm` after sourcing `tmuxinator.zsh` in zsh, you're still out of luck.

**Comment by cinaeco** [comment]
Yeah, that won't work, and that's kind of the problem with trying to setup zsh completion by direct sourcing. This is where using zsh's `fpath` to load the completion file shows its strength, because it will only run the contents of `tmuxinator.zsh` at completion time, well after rvm or any ruby thing is initialised.

Of course, `fpath` needs a bit more cognitive load to set up - e.g. the file Must be called `_tmuxinator` and `fpath` Must be defined before whenever `compinit` is called (usually in prezto or OMZ) - so I understand people might not like that. Still, it's the more correct way.

**Comment by cinaeco** [comment]
Hm. Actually, with direct sourcing, we can keep parity between `bash` and `zsh` if run `compdef` instead of `_tmuxinator` directly in `tmuxinator.zsh`.

```
compdef _tmuxinator tmuxinator mux
```

**Comment by cinaeco** [comment]
You know what, I might just make a pull request.

**Comment by J3RN** [comment]
@cinaeco Are we good to close this issue?

**Comment by cinaeco** [comment]
@J3RN yes we are. Thanks!
