### ISSUE TITLE
Only part of window command running after upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by jc00ke** [tmuxinator/tmuxinator#414]
I upgraded from Ubuntu 15.10 to 16.04 (now using Gnome terminal 3.18.3) and now when I go to start a project the command I have set for my `editor` window "partly" runs.

```
➜ cat ~/.tmuxinator/api.yml
# ~/.tmuxinator/api.yml

name: api
root: ~/projects/api

windows:
  - editor: nvim README.md
  - console:
  - mix: mix deps.get; and exit

➜ mux start api

DME.md
➜ api DME.md
DME.md: command not found
➜ api 

➜ tmuxinator -v
tmuxinator 0.8.1

➜ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

Happy to provide any other settings or run commands.

**Comment by ethagnawl** [comment]
Could you share the output of `tmuxinator debug api`?

**Comment by jc00ke** [comment]
```
➜ ~ tmuxinator debug api
no server running on /tmp/tmux-1000/default
#!/usr/bin/fish

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

  cd /home/jesse/projects/api

  # Run pre command.
  

  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s api -n editor


  # Create other windows.
  tmux new-window  -t api:2 -n console
  tmux new-window  -t api:3 -n mix


  # Window "editor"
  tmux send-keys -t api:1 nvim\ README.md C-m

  # Window "console"

  # Window "mix"
  tmux send-keys -t api:3 mix\ deps.get\;\ and\ exit C-m

  tmux select-window -t 1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t api
  else
    tmux -u switch-client -t api
  fi

```

**Comment by jc00ke** [comment]
Hmm, that `\ ` escaping looks like it might be causing the issue.

```
> irb -rshellwords
"nvim README.md".shellescape
=> "nvim\\ README.md"
```

**Comment by ethagnawl** [comment]
That could very well be... 

Out of curiosity, have you tried starting the project using Bash?

**Comment by jc00ke** [comment]
I had not, just did, and it worked.

**Comment by ethagnawl** [comment]
@jc00ke Okay - that's good to know.

Unfortunately, I'm unable to reproduce this issue on Debian 8, using Fish 2.2.0.

Maybe someone else who has access to a 16.04 environment can chime in?

**Comment by fbertux** [comment]
Same here. 
I'm using Arch Linux with tmux 2.2 and tmuxinator 0.8.1. With tmux 2.1 this error doesn't appears.
When I start a tmuxinator session, I get the error "no server running on /tmp/tmux-1000/default" on the first pane, all others panes open with the expected command. This only happens when there's no tmux sessions running on system. For example if I run tmuxinator start session_a and then tmuxinator start session_b, I get the error only on session_a and session_b works as expected.
Using Debian Jessie with tmuxinator 0.8.1 and tmux 2.1 the same error appears.

**Comment by autumnlansing** [comment]
I'm getting this same issue after a recent upgrade from Fedora 23 to 24. As with @fbertux, I receive the "no server running" message, and it only happens if there are no other tmux sessions running.

Tmux was updated to 2.2 from 2.1 during the upgrade. The issue happens with both tmuxinator 0.7.1 and 0.8.1. The problem didn't occur on Fedora 23. I use zsh for my shell.

**Comment by ethagnawl** [comment]
Upon further inspection, I'm also seeing a `failed to connect to server: Connection refused` message _only_ when running `tmuxinator start $PROJECT` or `tmuxinator debug $PROJECT` outside of a Tmux session. Though, in my case, if I do start the project, all commands are executed without issue. (Environment is Debian 8, Tmux 1.9, Tmuxinator 0.8.1 and Bash/Fish.)

**Comment by jc00ke** [comment]
@ethagnawl works on my machine, thank you!
