### ISSUE TITLE
Ruby 1.9.3 Broken Development Dependency term-aniscolor 

### ISSUE THREAD

**Issue by seanmalloy** [tmuxinator/tmuxinator#465]
Travis CI tests are failing for all Ruby 1.9.3 builds. Gem term-ansicolor >= 1.4.0 no longer supports Ruby 1.9.3. See below error for details.

https://travis-ci.org/tmuxinator/tmuxinator/jobs/164456620

```
$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
term-ansicolor-1.4.0 requires ruby version >= 2.0, which is incompatible with
the current version, ruby 1.9.3p551
The command "eval bundle install --jobs=3 --retry=3" failed. Retrying, 2 of 3.
```

**Comment by J3RN** [comment]
@seanmalloy Thanks for digging into this! To remedy this, I think perhaps the best solution would be for us to withdraw our support for Ruby 1.9.3 (which I did in #467), since 1.9.3 is no longer supported.

A quick check seems to show that Debian is shipping Ruby 2.1.5 these days, and macOS appears to be shipping Ruby 2.0.0. Without us having the data to know for sure, I imagine most users would not be impacted by the removal.

@ethagnawl @adamstrickland Thoughts?

**Comment by ethagnawl** [comment]
@J3RN That sounds reasonable to me. [ruby-lang.org EOL'd Ruby 1.9.3 in February 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/).

**Comment by adamstrickland** [comment]
Yeah, I agree.  1.9.3 isn't supported any longer, I don't see why we'd continue supporting it.
