### ISSUE TITLE
tmuxinator edit [project]

### ISSUE THREAD

**Issue by LoveIsGrief** [tmuxinator/tmuxinator#498]
It would be great to be able to edit existing projects without having to navigate to the project directory first. The command could call up the configured system editor to started editing the given project.

**Comment by ethagnawl** [comment]
> It would be great to be able to edit existing projects without having to navigate to the project directory first.

This is how `tmuxinator edit [project]` _should_ behave for standard tmuxinator projects. If this is the scenario you're referring to and you're not seeing this behavior: ensure `$EDITOR` has been defined and if the problem persists, please provide some additional data about your environment (tmuxinator version, OS/version, etc.)

Otherwise, are you referring to editing local project files? (e.g. ~/projects/something/.tmuxinator.yml) If so, this _could_ work, but would add _a lot_ of overhead to `edit`, `delete`, etc. as they'd have to either maintain an index of local project file locations and names or traverse the entire filesystem to find the given local project config file.

**Comment by LoveIsGrief** [comment]
Ah, indeed the option exists, but I only discovered it because of completions.

```bash
$ tmuxinator version
tmuxinator 0.9.0
$ tmuxinator --help
tmuxinator commands:
  tmuxinator commands                          # Lists commands available in tmuxinator
  tmuxinator completions [arg1 arg2]           # Used for shell completion
  tmuxinator copy [EXISTING] [NEW]             # Copy an existing project to a new project and open it in your editor
  tmuxinator debug [PROJECT] [ARGS]            # Output the shell commands that are generated by tmuxinator
  tmuxinator delete [PROJECT1] [PROJECT2] ...  # Deletes given project
  tmuxinator doctor                            # Look for problems in your configuration
  tmuxinator help [COMMAND]                    # Describe available commands or one specific command
  tmuxinator implode                           # Deletes all tmuxinator projects
  tmuxinator list                              # Lists all tmuxinator projects
  tmuxinator local                             # Start a tmux session using ./.tmuxinator.yml
  tmuxinator new [PROJECT]                     # Create a new project file and open it in your editor
  tmuxinator start [PROJECT] [ARGS]            # Start a tmux session using a project's tmuxinator config, with an optional [ALIAS] for project reuse
  tmuxinator stop [PROJECT]                    # Stop a tmux session using a project's tmuxinator config
  tmuxinator version                           # Display installed tmuxinator version

# Completions
$ tmuxinator 
baldr         completions   debug         doctor        implode       local         open          stop          version       
commands      copy          delete        edit          list          new           start         test-cluster  
```

So this issue would be more with the incomplete help ;)

**Comment by ethagnawl** [comment]
> So this issue would be more with the incomplete `help`

Unfortunately, this is because `edit` is actually an alias of `new` and, as such, doesn't get its own `help` entry. This is a [known issue](https://github.com/tmuxinator/tmuxinator/issues/420) and will - hopefully - be addressed soon.

I'm going to close this issue, but feel free to re-open if you think there's more to discuss.
