### ISSUE TITLE
Suggest updating supported ruby versions

### ISSUE THREAD

**Issue by adamstrickland** [tmuxinator/tmuxinator#524]
Support for Ruby 2.0 and 2.1 has ended.  Suggest moving supported versions to 2.2, 2.3 and 2.4.  Further, suggest a policy to only support ruby versions that are themselves currently supported as a project policy.  Thoughts?

**Comment by adamstrickland** [comment]
@tmuxinator/tmuxinator any thoughts on this?  While we're on the topic, do we feel there's a reason to (or not to) deprecate support for some of the older versions of tmux, as well? We currently support back to tmux 1.5, which was released 6+ years ago.

**Comment by ethagnawl** [comment]
Keeping pace with the officially supported versions of Ruby sounds reasonable. However, I'm not aware of any issues which have surfaced as a result of people using legacy versions. It seems like the major downsides of continuing support for legacy versions are: the library can't make use of some of the newer features (e.g. squiggly heredocs in `Cli::COMMANDS`) and the additional time added to the CI job.

I feel more strongly about dropping support for legacy versions of tmux because there are (at least two) conditionals which test for version ranges. 

I don't have much to offer in terms of suggesting which versions of tmux we drop support for - this calls to mind #427. Though, one data point which might be worth mentioning is that the latest version of Debian (Stretch) offers 2.3 and the most recent "obsolete stable release" (Jessie) offers 1.9-6. Depending on what other distributions/OSs are offering, drawing the line at 1.9* would seem reasonable to me.

**Comment by ethagnawl** [comment]
Per #538 and @adamstrickland's [comment](https://github.com/tmuxinator/tmuxinator/issues/536#issuecomment-307885272) in #536, perhaps we should also consider adopting an upper bound on the supported version of tmux?

**Comment by techgaun** [comment]
I feel at least, the `master` branch deserves a basic support in terms of supporting existing commands. My problem specifically was that due to the version check, the tmux master was generating command that're supposed to be the commands for older version of tmux. Its of course not always possible to support new additions or changes but it would at least be great to default to the newer command sets.

**Comment by alexkrolick** [comment]
Mac OS ships Ruby 2.0 as the system Ruby, so this is kind of annoying. Is there a technical reason to require a higher version?

**Comment by ethagnawl** [comment]
We've been tracking the supported Rubies for a while now and have updated the docs to reflect that. Feel free to reopen if there's anything else to discuss.
