### ISSUE TITLE
Missing post option

### ISSUE THREAD

**Issue by mstruebing** [tmuxinator/tmuxinator#588]
Since the post option is deprecated and replaced by project hooks I couldn't find a project hook that's hooking in on that moment.

To describe my use case:

* I start my terminal
* my terminal autostarts tmux
* I start my dashboard(I'm just calling it like this, it's my main session, where updates are run, irc, mails etc.)
* the first tmux-session is still present. 

I had `post: tmux kill-session -t 0` in there before and it worked like  a charm.

So, am I overlooking something or isnt' there really a projekt hook to achieve this? If I do this on project_start the tmux session gets killed before the other even started resulting in my terminal to close.

**Comment by jakubrohleder** [comment]
I have similar problem, I use tmuxinator with iTerm terminal, which has a native tmux support (with tmux -CC option). My configuration was:

```
attach: false
post: tmux -CC attach -t my_session
```

After changing `post` to `on_project_start` tmux reports an error if session does not exist yet (it is no reattached).

**Comment by ethagnawl** [comment]
@endorama Any thoughts on this? Do you think it would make sense to add a `hook_after_project_start` hook? If so, that begs the question of whether the other hooks should receive similar treatment and, perhaps, be given more descriptive names (e.g. `hook_before_project_start`).

**Comment by endorama** [comment]
Hi all!

I suspect the correct hook to use in case presented by @mstruebing would be `on_project_exit`, not `on_project_start`. If I got it right, you want to execute an action when exiting the attached session from `tmuxinator`. If this is the case, the same behaviour of the `post` action is retained by the `on_project_exit` hook.

This is implemented lines https://github.com/tmuxinator/tmuxinator/blob/63009373840109a4045f780362109ce7273ac119/lib/tmuxinator/assets/template.erb#L95-L99 

The case presented by @jakubrohleder is a bit different, but would probably work with the `on_project_exit` hook too, as the `post` and `on_project_exit` are executed in the same moment. 
As this case seems to be related to a custom attach command, and the `attach: false` with `post: tmux attach` is the documented way to specify a custom attach command; would probably be best to add a `custom_attach_command` option?

@mstruebing @jakubrohleder could you please try to use `on_project_exit` for your use cases? If that works and I correctly understood what you are trying to achieve, I would open a new issue for the case presented by @jakubrohleder, while discussing how to clarify the relation between the `on_project_exit` and `post` options.

Naming unfortunately is a bit difficult to get right due to how the session creation and attaching works in the start tmuxinator script: 
- when `attach: true` `post` and `on_project_exit` are being executed on session detach
- when `attach: false` `post` and `on_project_exit` are being executed before session attach ( because attaching does not happen )

@ethagnawl I'm open to adding new hooks if needed or renaming the current ones, I'd like to clarify the use cases though.

**Comment by mstruebing** [comment]
No it's on project exit. I try to explain it again.

I start my terminal
My terminal autostarts tmux
So I have already one session
I start my main session with tmuxinator (autostart multiple panes with updates, emails, irc, etc.)
I want to have this main session alone and no other session at all.
So I need to kill the first session autostarted by my terminal manually.

Before this was possible to do automatically with the post option.

Hope this makes it a bit clearer for what I've used the post option.

**Comment by endorama** [comment]
@jakubrohleder as your issue seems related to https://github.com/tmuxinator/tmuxinator/issues/581 and I would continue the discussion there. Please have a look at https://github.com/tmuxinator/tmuxinator/issues/581#issuecomment-418168094

**Comment by endorama** [comment]
@mstruebing I'm sorry I think I'm missing something in your configuration.

> I want to have this main session alone and no other session at all.
> So I need to kill the first session autostarted by my terminal manually.

Are you using the `attach: false` option? 
I get your use case, and the `on_project_start` hook would be appropriate in your case. But I don't get how that would work using `post`: `post` is run **after** the "tmuxinator session" has been configured, independently from the `attach` option. In any case if `post` works, `on_project_exit` ( even if the name suggest otherwise ) should work too.

Could you post your project configuration and the result of `tmxuninator debug <project>`?

**Comment by mstruebing** [comment]
@endorama When I use the `post:` option it closes my terminal (my terminal autocloses if no tmux session is present) before the new session gets created by tmuxinator.

`on_project_exit` kills the 'autocreated session by my terminal' when I exit the tmuxinator session, which would be expected behvaiour for me, but since I'm switching between many different sessions during my day there is always that not needed 'first session' which adds cognitive complexity (even if not much).

`attach: false` doesn't do what I want either, it just leaves me in the 'autocreated by my terminal' session.

[vid.tar.gz](https://github.com/tmuxinator/tmuxinator/files/2347142/vid.tar.gz)


I've added a video which should made clear what I mean

**Comment by mstruebing** [comment]
Thanks @endorama - I will try your suggestions at first and if it will not work I try to make a more in depth explanation of what I want to achieve and how does it currently work.
