### ISSUE TITLE
Running tmux set commands?

### ISSUE THREAD

**Issue by Andy-ABTec** [tmuxinator/tmuxinator#589]
Apologies if I'm being "thick", I'm new to tmux (and very new to tmuxinator).

First off thanks for a great tool, finally tmux is usable for me! One thing I can't figure out however is can I include tmux set commands in the tmuxinator config?

I'm actually using tmuxinator on Windows 10 through WSL to monitor a local gh-pages build and I'd like to include a "set -g mouse on" so it fits my workflow better but can't figure out where to put it in the config (or does it have to go in the tmux config?)

Grateful of any advice...

**Comment by spewnm** [comment]
If you want `set -g mouse on` to be part of your every tmux session, include that in your tmux configuration(usually `~/.tmux.conf`, I don't know about WSL).

In case you want `set` commands for specific tmuxinator projects, however, I don't know how to help you because I'm having trouble with that myself. :sweat_smile: 

I'm used to [tmuxp](https://github.com/tmux-python/tmuxp) letting me include something like `status: on` in the YAML config. I tried sourcing a modified `.tmux.conf` with `-f`, but I guess the tmux server only reads the config when it starts up and it isn't actually session-based.

**Comment by Andy-ABTec** [comment]
Thanks for that...

**Comment by spewnm** [comment]
In case you meant the latter, by the way, here's what I'm doing right now to `set status on` on two of my tmuxinator projects (note: I have `set -g status off` for any other session):

```yaml
name: comms
root: ~/
windows:
  - irc:
      - tmux set status on
      - weechat
  - mail: neomutt
```
