### ISSUE TITLE
"tmuxinator stop" without arguments

### ISSUE THREAD

**Issue by LavaToaster** [tmuxinator/tmuxinator#626]
You can `tmuxinator start` in a directory, but you aren't able to `tmuxinator stop` without adding something so it doesn't complain about missing arguments.

Is it possible to remove this requirement?

**Comment by ethagnawl** [comment]
Hi, @Lavoaster. I think this is a great idea and would be happy to put it up for consideration.

**Comment by ethagnawl** [comment]
I made a quick first pass at this a few weeks ago (sniffing out a name if none is provided via `tmux display-message -p '\#{session_name}' 2> /dev/null`) and hit upon the following issues:

- Will wantonly kill most recently created tmuxinator session if run outside session. Seems reasonable?
- Will fail with "Project foo-1 doesn't exist." if run inside named tmux session named foo-1. This is probably fine.
- Where should the session name sniffer live?
- Can it always be called safely?

Does anyone have thoughts on any of the above? /cc @tmuxinator/tmuxinator

**Comment by raiyuza** [comment]
Firstly , +1 I would like this as well. So often i use kill-session instead of stop since the combination of META+B :kill-server is sometimes just faster in my workflow.

> * Will wantonly kill most recently created tmuxinator session if run outside session. Seems reasonable?

No, or ask for confirmation.  It should always use the current sessions as context.

> * Will fail with "Project foo-1 doesn't exist." if run inside named tmux session named foo-1. This is probably fine.

Why does this behavior happen? Is it because you can't parse the "-" ? If so it's a solvable imperament. 

> * Where should the session name sniffer live?

IMO, It should build a buffer of active sessions when you call the cli command on, [stop, start]. (In the bootstrap component or maybe within the function of stop it just "queries"  then.

> * Can it always be called safely?

IMO Requirements are as followed

1. Current session name is a match in said buffer (list of sessions)
2. No active processes are running (background jobs etc) in said session
3. If the env variable "ask_for_conformation" (orso) is set, which defines if a prompt is displayed for confirmation 

I could implement this feature if @ethagnawl agrees!
