### ISSUE TITLE
tmux logs in the current directory

### ISSUE THREAD

**Issue by Shamaoke** [tmuxinator/tmuxinator#680]
The tmux log files `tmux-client-1111.log` and `tmux-server-1112.log` are created in the current directory after starting a tmux session through tmuxinator. These files litter the project directory, so they should be created in some other location or not be created at all.

I start a session with the following command `tmuxinator start simple`. The “simple” layout has the following structure:

    name: <%= @args[0] || (File.basename Dir.pwd) %>

    startup_pane: 1

    windows:
      - editor: vim
      - work:
      - build|install:
          layout: even-horizontal
          panes:
            -
            -
      - console:
      - git:
          layout: 28ed,157x45,0,0{78x45,0,0,52,78x45,79,0[78x22,79,0,57,78x22,79,23,58]}
          panes:
            - watch -ctn 1 git\ godlog
            - watch -ctn 1 git\ st
            -
      - man:
          layout: even-horizontal
          panes:
            -
            -
      - fm: vifm

_tmuxinator 0.15.0_
_tmux 2.8_
_Ruby 2.6.0_
_Linux (Arch)_

**Comment by raiyuza** [comment]
Hey Man, 

This is default behavior of _tmux_ not tmuxinator. You could have found out by googling for a bit. Things i found.

- The manpage only references logging at one place.

```
-v            Request verbose logging.  Log messages will be saved into
                   tmux-client-PID.log and tmux-server-PID.log files in the
                   current directory, where PID is the PID of the server or
                   client process.  If -v is specified twice, an additional
                   tmux-out-PID.log file is generated with a copy of every‐
                   thing tmux writes to the terminal
```
I **assume** that when something goes wrong (or you call tmux with -v in some wrapper script and or function) it calls the underlying verbose function(-v flag)


- The second result in google with the search term "_tmux default log location_"  will get you get [this thread](https://www.reddit.com/r/tmux/comments/2b178v/tmux_log_files_in_home_folder/). 

This assumption gets more evidence in one of the replies eg.

> Those are logs created directly by tmux. Are you starting it with the verbose-flag (-v) by chance?
> 
> Ninja edit:
> The log-files are stored in the folder you're starting the tmux-server. So if you want them in another folder, start tmux in ~/.tmuxlogs for example.
> 
> man tmux has all the information about this. 
 
Tbh , i couldn't find it clearly written in the manpage of my version of tmux (2.3) so it might be in newer versions. 

Nevertheless, there are 3 ways to fix your problem 

1.  Be creative with tmuxinator, less effort and not really contributing anything to actually solve this problem more patching a symptom.

```
root: /var/log/tmuxinator

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: cd <actual_root>

windows:
  - IDE: $EDITOR .
```

Don't forget to make a keybinding in like this in your tmux.conf, otherwise all your new windows will be started in "_/var/log/tmuxinator_"
```
bind c new-window -c "#{pane_current_path}"
```

2. Make a pull request at tmux/tmux and explain them what your trying to achieve.

> Feature: Make log file save location configurable.

orso.

3. We could fix this behavior in tmuxinator temporary by making  a config property ``logs_location``. It would the same behavior as the as described above before executing root. 

\
1. Start session in log location, from config key "logs_location"
2. Then set the root property
3. Go on as usual

Though morally i think tmux should be patching this rather then we making a workaround

¯\_(ツ)_/¯ 

I could make this patch (#3) for you if options 1 and 2  aren't feasible.

**Comment by ethagnawl** [comment]
Hi, @Shamaoke. 

I'm going to close this in accordance with what @raiyuza said above: it's (arguably) a tmux "issue". They also made a few nice suggestions and I'd suggest looking into #1. You could also want to consider using the [tmux-logging](https://github.com/tmux-plugins/tmux-logging) plugin which would allow you to store your tmux logs in a structured way without having to resort to hacky tmuxinator based solutions.

**Comment by Shamaoke** [comment]
I observe this behavior since I update tmuxinator from 0.13.0 to 0.15.0. Before that, in the _same environment_, tmux didn't create any logs in the current directory. Moreover, it don't create them now if I run the program not through tmuxinator.

So, the issue is definitely related to tmuxinator itself, not tmux, and I think, the thread shouldn't be closed.

**Comment by ethagnawl** [comment]
Could you include the output of `tmuxinator debug simple`?

**Comment by raiyuza** [comment]
Shame though , means there is a hidden edge case somewhere in 0.13. Too bad.

**Comment by Shamaoke** [comment]
@raiyuza The problem came up right after I update tmuxinator. At first, I thought that these changes were intended, but as it turned out they wasn't. After I restarted my computer, the problem disappeared. Perhaps I updated some other soft and the operation of the program was affected by that fact.

Thanks for your analysis of possible solutions to the problem.

**Comment by raiyuza** [comment]
Aaah probably some interaction with rbenv or $PATH i guess, forgot to run exec zsh || zsh rehash orso i think!
