### ISSUE TITLE
Provide a handler which is performed at the very end of project loading

### ISSUE THREAD

**Issue by Shamaoke** [tmuxinator/tmuxinator#821]
I want to run a script that change the terminal window title (actually, the terminal tab title) after project finish loading.

I have the `set -g set-titles on` setting in `tmux.conf`. This setting allows tmux to automatically change terminal title by the name of the currently started session. If I hook my script on the handlers which is available in tmuxinator at present, tmux rewrites its result, so the task can't be accomplished.

I propose to add a project hook which is performed at the very end of project loading, so that you can perform actions the result of which couldn't be rewritten by any following actions in the process of project loading.

I'd call the hook `on_project_ready`.

**Comment by endorama** [comment]
@Shamaoke hello! I contributed the "hooks" feature a while back so let me jump in. In not entirely sure what you propose is feasible. I remember that due to how `tmuxinator` works there were some limitations to what hooks is possible to implement. 

May I ask you to try implementing a stub versions of it to test if it suite your use case? 
You may do that without touching any code: dump the template that `tmuxinator` runs when starting a project with `tmuxinator debug <project>` and do manual edits to achieve your desired result. You can run the resulting script as a normal shell script. 
This way we can agree on this feature behaviour before any code edits. What do you think?

**Comment by Shamaoke** [comment]
@endorama I've followed your suggestion and tried to edit the generated script inserting my hook script in different parts of it. Unfortunately, the hook script didn't work as I expected wherever I put it in. Apparently, the desired feature either can't be implemented or its implementation will be too involved, so the case can be closed. Thank you for your attention to it.

**Comment by endorama** [comment]
No worries! I remember there was something fishy around that feature, as I would love to use it too 😅

Thanks for trying though, highly appreciated.

(I can't close this so I'll leave that to a maintainer stopping by; thanks!)
